### ISSUE TITLE
更改密碼後無法登入

### ISSUE THREAD

**Issue by watercatuwu** [BWsix/clhs-scoreboard#158]
### 選擇訊息類型

改善建議

### 內容

智慧校園平台更改過密碼後就不能再改回身分證字號了
而密碼的input似乎有綁像html pattern之類的驗證機制?
希望能改善密碼只能用身分證字號登入的部分:)

**Comment by BWsix** [comment]
原來可以改密碼👀

**Comment by BWsix** [comment]
@watercatuwu 已經修好了，謝謝你~
這個問題比discord webhook壞掉好修多了QQ

**Comment by watercatuwu** [comment]
不客氣🥰🥰
