### ISSUE TITLE
錯誤：帳號密碼無誤，但發生錯誤無法登入

### ISSUE THREAD

**Issue by weedfish1** [BWsix/clhs-scoreboard#164]
### 選擇訊息類型

錯誤回報

### 內容

3/25的更新後，登入會出現：「錯誤：帳號密碼無誤，但發生錯誤無法登入」（沒有修改過密碼）

**Comment by BWsix** [comment]
學校成績查詢系統又又又更新了登入邏輯
應該暫時修好了，但有可能是因為最近學校正在更新系統所以才有這次的問題?之後再看看吧
