### ISSUE TITLE
高中生資訊網

### ISSUE THREAD

**Issue by Howie0715** [BWsix/clhs-scoreboard#48]
### 標題

高中生資訊網

### 作者名稱

壢中72屆同學主導（部分文章由台灣高中生、教育界人士撰寫）

### 作品介紹

高中生資訊網創立於2020年，配合108課綱推行。希望藉由協助學生統整資訊，縮短學生的資訊落差，進而達到學習平等的目標。 

### 作品連結

https://students.tw/

### 背景圖片連結

https://imgur.com/a/V9r0o3L

**Comment by BWsix** [comment]
Looks great to me!

**Comment by BWsix** [comment]
兩小時內會自動更新，謝謝分享👍
